### ISSUE TITLE
15 на прелоадере если есть проблема с ipfs то должно показано быть, что мол сигнальный сервер в дауне

### ISSUE THREAD

**Issue by apelsin555** [swaponline/alpha.swap.online#14]
15 на прелоадере если есть проблема с ipfs то должно показано быть, что мол сигнальный сервер в дауне

**Comment by caffeinum** [comment]
![image](https://user-images.githubusercontent.com/1909384/40165761-8079477e-59c5-11e8-8b01-c862dab48d37.png)
@rmixi

**Comment by caffeinum** [comment]
#32
