### ISSUE TITLE
22 не давать стартовать заявку если нет на счету денег

### ISSUE THREAD

**Issue by apelsin555** [swaponline/alpha.swap.online#21]
22 не давать стартовать заявку если нет на счету денег

**Comment by rmixi** [comment]
готово

**Comment by caffeinum** [comment]
@rmixi 
Ордера:
![image](https://user-images.githubusercontent.com/1909384/40111224-e2a70c30-590a-11e8-9810-e4663c2bf5f4.png)

Баланс:
![image](https://user-images.githubusercontent.com/1909384/40111233-ec217a0c-590a-11e8-8834-31dea5878f4e.png)

**Comment by caffeinum** [comment]
https://github.com/swaponline/alpha.swap.online/commit/913a7ded9cc713e5bc833630203c05f0a7335b3c#r28997455
