### ISSUE TITLE
Можно принять заявку, даже если на счету нет средств

### ISSUE THREAD

**Issue by caffeinum** [swaponline/alpha.swap.online#29]
- создал ордер
 - вывел деньги наружу
 - кто-то одобрил ордер
 - принял заявку
 - ордер доходит до конца у одного из чуваков, у второго зависает на последнем пункте:

![image](https://user-images.githubusercontent.com/1909384/40115843-6bf3a476-591a-11e8-81f3-7c725c36b4af.png)

часть транзакций в эфире проходят нормально, часть фэйлится

**Comment by rmixi** [comment]
добавил статус заказа
