### ISSUE TITLE
Ошибка 6 (не работает кнопка рефреш в балансе)

### ISSUE THREAD

**Issue by apelsin555** [swaponline/alpha.swap.online#5]
Ошибка 6 (не работает кнопка рефреш в балансе)
При выводе денег со счетов, после успешного вывода денег, не обновляется баланс на новый. Жмёшь на кнопку рефреш - не помогает. Жмёшь на кнопку обновления страницы в браузере, баланс тоже не изменяется. Видео на примере вывода эфира https://yadi.sk/i/9_9vYx5F3Vxxri Пробовал в фирефокс/яндекс браузер (свежие версии)

**Comment by rmixi** [comment]
https://github.com/swaponline/alpha.swap.online/issues/6
