### ISSUE TITLE
Ошибка 8 (можно обменять деньги по не правильному курсу)

### ISSUE THREAD

**Issue by apelsin555** [swaponline/alpha.swap.online#7]
При создании оффера, можно произвести обмен эфира/биткойна/ноксонов не своему курсу. Т.е. в норме эфир должен обмениваться по курсу эфира, биткойны по курсу биткойна и т.д. У нас же есть лазейка.

   1. Для этого надо выбрать любое из направлений обмена (при создании оффера).
   2. Далее ввести сумму обмена, чтобы в полях купить-продать проставили числовые значения.
   3. И после поменять направление обмена на отличное, от ранее проставленного (т.е. если покупал биткойн, можно поставить ноксоны или эфиры). И соответственно в поле "куплю" останется стоять старый курс от биткойна (или того, что там стояло), не правильный. И соответственно по не правильному курсу создаётся успешно заявка, и её с не правильным курсом можно обменять.

**Comment by caffeinum** [comment]
Так курс ты сам выставляешь. Другое дело, что при нажатии на кнопку нужно курс тоже инвертировать

![image](https://user-images.githubusercontent.com/1909384/40115210-59ef96b0-5918-11e8-94fb-7a29afdb26a2.png)
![image](https://user-images.githubusercontent.com/1909384/40115219-61f7d886-5918-11e8-8d8d-0204c68fd59a.png)

**Comment by caffeinum** [comment]
@rmixi тут баг в том, что у тебя цифры не меняются между полями, когда ты нажимаешь стрелочки. На скриншоте выше справа должно было стать 13 - 1, а не 1 - 13.

Просто неинтуитивно
